-- Revert decision graph schema
DROP INDEX IF EXISTS idx_context_node;
DROP INDEX IF EXISTS idx_edges_to;
DROP INDEX IF EXISTS idx_edges_from;
DROP INDEX IF EXISTS idx_nodes_status;
DROP INDEX IF EXISTS idx_nodes_type;
DROP TABLE IF EXISTS session_nodes;
DROP TABLE IF EXISTS decision_sessions;
DROP TABLE IF EXISTS decision_context;
DROP TABLE IF EXISTS decision_edges;
DROP TABLE IF EXISTS decision_nodes;
